const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Gada Darshan";
const email = "Email";
const emailHint = "Admin@admin.dart";
const password = "Password";
const passwordHint = "********";
const forgetpassword = "ForgetPassword?";
const login = "Login";
const signup = "signup";
const createnewaccount = "Create New Accout";
const loginwith = "Log in With";
const retyrppassword = "Retype Password";
const retypepassHint = "Retype password";
const name = "Name";
const nameHint = "Gada Darshan";
const privacyPolicy = "PrivacyPolicy";
const termANDcond = "Terms And Condition";
const alreadyhaveaccount = "Already Have An Account ? ";
//home  .dart
const home = "Home",
    categories = "Categroies",
    cart = "Cart",
    account = "Account";
//home screen .dart
const searchanything = "Search anything ....",
    todaysdeal = "Today's deal",
    flashsales = "Flash Sale",
    topsellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    feturedCategories = "FeaturedCategories";
